apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mynginxapp
  name: mynginxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginxapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mynginxapp
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
