apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginxhttps
  name: nginxhttps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxhttps
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxhttps
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      containers:
      - image: dileepbg/nginx_test:v3
        name: nginx
        resources: {}
        ports:
        - containerPort: 443
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
status: {}